# Generated by Django 3.2 on 2023-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230525_1229'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('moderator', 'moderator'),
                    ('admin', 'admin'),
                    ('user', 'user'),
                ],
                default='user',
                max_length=20,
            ),
        ),
    ]
