# Generated by Django 3.2 on 2023-05-25 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20230525_1232'),
        ('users', '0004_alter_user_role'),
    ]

    operations = []
