# Generated by Django 3.2 on 2023-05-25 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_user_role'),
        ('users', '0006_alter_user_role'),
    ]

    operations = []
