# Generated by Django 3.2 on 2023-05-26 11:01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_merge_0005_alter_user_role_0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('admin', 'admin'),
                    ('user', 'user'),
                    ('moderator', 'moderator'),
                ],
                default='user',
                max_length=20,
            ),
        ),
    ]
