# Generated by Django 3.2 on 2023-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('moderator', 'Модератор')], default='user', max_length=20),
        ),
    ]
