# Generated by Django 3.2 on 2023-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('moderator', 'Модератор'), ('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=20),
        ),
    ]
